[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mosecapy"
dynamic = ["version"]
description = "use of moseca"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
  "click>=8.1.7",
  "demucs==4.0.0",
  "librosa==0.10.0.post2",
  "numpy<2",
  "onnx>=1.19.1",
  "onnxscript>=0.7.1",
  "pydub==0.25.1",
]

[project.scripts]
mosecapy = "mosecapy:cli"
export = "mosecapy.export_model:main"

[tool.uv]
constraint-dependencies = ["lameenc==1.8.1"]

[tool.hatch.version]
path = "src/mosecapy/__init__.py"

[tool.ruff]
line-length = 140
